name: Publish Docker image
on: [ push ]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Running this job only for master branch
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      # Must set up Docker Buildx, otherwise `push` input in docker/build-push-action@v2 won't work.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/zmrenwu/docker-postgresql:latest
          cache-from: type=registry,ref=ghcr.io/zmrenwu/docker-postgresql
          cache-to: type=inline